# Deploy 'public' to 'gh-pages' on commit
name: CI

# Only trigger when pushing to master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Download master brach
      - uses: actions/checkout@v2

      # Cache node_modules if possible
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Intall deps
      - name: Install Dependencies
        run: npm install

      # Runs the deploy command
      - name: Deploy website to gh-pages
        run: npm run deploy
