# Deploy 'public' to 'gh-pages' on commit
name: CI

# Only trigger when pushing to master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Download master brach
      - uses: actions/checkout@v2

      # Runs the deploy command
      - name: Deploy website to gh-pages
        run: npm run deploy
